### ISSUE TITLE
Precompute rows generation

### ISSUE THREAD

**Issue by Lynesth** [php-school/cli-menu#106]
Why do we always recompute getRows() ?

Couldn't we save the result and only recompute it if the contentWidth (or anything else needed to get the correct outout, like if the text was modified) has changed ?

This is something we could do for all MenuItems with 2 variants for selectable ones.

What do you say @AydinHassan ?

**Comment by AydinHassan** [comment]
I guess because we never thought of it or noticed any performance issues. I'm not sure on this, if we can do it without changing loads of code I don't see why not, how do you see a prototype working?

**Comment by Lynesth** [comment]
Yes we shouldn't need to modify much.

When we create a new item, we store its state (its text, if its itemExtra should be shown, etc).
The first time we call getRows, we generate the rows and save them in a new private variable.

Afterwards, when we call getRows, we compare the current state of the item with the stored one. If they are the same we just return the rows previously saved. If not we store the new state and regenerate/store the rows.

Not sure I made myself clear, let me know.

**Comment by AydinHassan** [comment]
I guess I mean would we have to do this for every item, eg code change in each item? Or could we just do it one place - like a item caching decorator or something

**Comment by AydinHassan** [comment]
Not a high priority for now. Open for discussion though!
