### ISSUE TITLE
Force terminal to return 8 colours in tests

### ISSUE THREAD

**Issue by Lynesth** [php-school/cli-menu#113]
In https://github.com/php-school/cli-menu/blob/master/test/Util/ColourUtilTest.php shouldn't we force the terminal to return 8 colours where we expect it to be ?

I mean that it's currently relying on the fact that Travis' terminal returns 8 colours when asked but it could change at some point.

@AydinHassan

**Comment by AydinHassan** [comment]
It is mocked to return 8 where it needs to be or did I miss something?

**Comment by Lynesth** [comment]
Yep nevermind that.
