### ISSUE TITLE
Don't clear terminal until opening

### ISSUE THREAD

**Issue by AydinHassan** [php-school/cli-menu#12]
Is this possible?

Currently the terminal is cleared via some method in the `CliMenu` `__construct`

This messes with the unit tests in the workshop as I'm testing the factory which creates the menus, it clears all the text output from PHPUnit

**Comment by mikeymike** [comment]
I don't see why not. Tbh it would make a lot more sense as you may not want to show the menu until later in the application so clearing the screen maybe unwanted behaviour anyway
