### ISSUE TITLE
How to get the Title of a Menu

### ISSUE THREAD

**Issue by taytus** [php-school/cli-menu#162]
Hello guys!
I'm saving menus I'm creating in an array. These are going to be submenus of a parent menu.
The menus are being saved correctly, but I can't figure it out how to get their title. This is what my array contains:
`PhpSchool\CliMenu\Builder\CliMenuBuilder {#808
  -menu: PhpSchool\CliMenu\CliMenu {#813
    #terminal: PhpSchool\Terminal\UnixTerminal {#809
      -isCanonical: true
      -echoBack: true
      -width: 134
      -height: null
      -colourSupport: null
      -originalConfiguration: "gfmt1:cflag=4b00:iflag=6b02:lflag=200005cb:oflag=3:discard=f:dsusp=19:eof=4:eol=ff:eol2=ff:erase=7f:intr=3:kill=15:lnext=16:min=1:quit=1c:reprint=12:start=11:status=14:stop=13:susp=1a:time=0:werase=17:ispeed=9600:ospeed=9600"
      -input: PhpSchool\Terminal\IO\ResourceInputStream {#810
        -stream: stream resource {@1
          timed_out: false
          blocked: true
          eof: false
          wrapper_type: "PHP"
          stream_type: "STDIO"
          mode: "rb"
          unread_bytes: 0
          seekable: true
          uri: "php://stdin"
          options: []
        }
      }
      -output: PhpSchool\Terminal\IO\ResourceOutputStream {#811
        -stream: stream resource {@2
          timed_out: false
          blocked: true
          eof: false
          wrapper_type: "PHP"
          stream_type: "STDIO"
          mode: "wb"
          unread_bytes: 0
          seekable: true
          uri: "php://stdout"
          options: []
        }
      }
    }
    #style: PhpSchool\CliMenu\MenuStyle {#812
      #terminal: PhpSchool\Terminal\UnixTerminal {#809}
      #fg: "white"
      #bg: "blue"
      #width: 100
      #margin: 17.0
      #paddingTopBottom: 2
      #paddingLeftRight: 4
      -paddingTopBottomRows: array:2 [
        0 => "                 \e[43m  \e[37;44m                                                                                                \e[43m  \e[0m\n"
        1 => "                 \e[43m  \e[37;44m                                                                                                \e[43m  \e[0m\n"
      ]
      #contentWidth: 88
      -selectedMarker: "● "
      -unselectedMarker: "○ "
      -itemExtra: "✔"
      -displaysExtra: false
      -titleSeparator: "="
      -coloursSetCode: "\e[37;44m"
      -invertedColoursSetCode: "\e[7m"
      -invertedColoursUnsetCode: "\e[27m"
      -coloursResetCode: "\e[0m"
      -borderTopWidth: 1
      -borderRightWidth: 2
      -borderBottomWidth: 1
      -borderLeftWidth: 2
      -borderColour: "yellow"
      -borderTopRows: array:1 [
        0 => "                 \e[43m                                                                                                    \e[0m\n"
      ]
      -borderBottomRows: array:1 [
        0 => "                 \e[43m                                                                                                    \e[0m\n"
      ]
      -marginAuto: true
    }
    #title: "Landing Page Operations"
    #items: array:4 [
      0 => PhpSchool\CliMenu\MenuItem\SelectableItem {#815
        -selectAction: Closure {#814
          class: "App\MyClasses\CliMenu"
          this: App\MyClasses\CliMenu {#799 …}
          parameters: {
            $menu: {
              typeHint: "PhpSchool\CliMenu\CliMenu"
            }
          }
          file: "/Users/taytus/Projects/roboamp/app/MyClasses/CliMenu.php"
          line: "67 to 71"
        }
        -text: "Delete Landing HTML Page"
        -showItemExtra: false
        -disabled: false
      }
      1 => PhpSchool\CliMenu\MenuItem\SelectableItem {#816
        -selectAction: Closure {#814}
        -text: "Create Landing Page"
        -showItemExtra: false
        -disabled: false
      }
      2 => PhpSchool\CliMenu\MenuItem\LineBreakItem {#817
        -breakChar: "-"
        -lines: 1
      }
      3 => PhpSchool\CliMenu\MenuItem\SelectableItem {#818
        -selectAction: PhpSchool\CliMenu\Action\ExitAction {#819}
        -text: "Exit"
        -showItemExtra: false
        -disabled: false
      }
    ]
    #selectedItem: 0
    #open: false
    #parent: null
    #defaultControlMappings: array:8 [
      "^P" => "UP"
      "k" => "UP"
      "^K" => "DOWN"
      "j" => "DOWN"
      "\r" => "ENTER"
      " " => "ENTER"
      "l" => "LEFT"
      "m" => "RIGHT"
    ]
    #customControlMappings: []
    -currentFrame: null
  }
  -goBackButtonText: "Go Back"
  -exitButtonText: "Exit"
  -style: PhpSchool\CliMenu\MenuStyle {#812}
  -terminal: PhpSchool\Terminal\UnixTerminal {#809}
  -disableDefaultItems: false
  -disabled: false
  -subMenu: false
}
`
I can access Terminal and Style... but I need to access the tittle as well.

Thank you!

**Comment by Lynesth** [comment]
You currently cannot acces the title outside of the menu. You can set it using `setTitle` (callable on both CliMenuBuilder and CliMenu) but not get it.

Why do you need to get it ? Could you show us the code/loop where you would need to access the title ?

Thank you :)

**Comment by taytus** [comment]
I have a couple of classes that I use from command line. Each class returns an array with the options and the methods associated to them.

The main class calls my own CliMenu generator. 

My CliMenu generator, takes each class (passed via the main class when instantiated) and creates a bunch of sub menus that I store in an array.

The idea is to have a main menu with all these classes options as sub menu.

That's why I'd like to have the sub menus titles so I can use those as options in the main menu. I can solve this and save those names in an array, I thought we had an easier way to get the title.

Here's my code (simplified)

`
//main class

private $menus_classes=['CliLandingPage','SOME_OTHER_CLASS];
public function handle(){
       $this->menu=new CliMenu($this->menus_classes);
        $this->menu->open_menu();

}

//menu generator
public function create_menu(){
        foreach ($this->classes as $class){
            $this->create_sub_menu($class);
        }
    }
public function create_sub_menu($class){

        $class=MyClasses::create_class_from_string($class,"CLI","");

        $class_menu= $class->menu();

        $menu_title=$class_menu['title'];
        $menu_items=$class_menu['items'];

        $menu = (new CliMenuBuilder)
            ->setTitle($menu_title);

        $callable=function(phps_cliMenu $menu){
            $item=$this->callables[$menu->selectedItem];
            $class=MyClasses::create_class_from_string($item['class']);
            call_user_func(array($class,$item['method']));
        };

        foreach ($menu_items as $item){
            $this->create_callable($item['method']);
            $menu->addItem($item['menu item'],$callable);
        }

       $menu->addLineBreak('-')
            ->setBorder(1, 2, 'yellow')
            ->setPadding(2, 4)
            ->setMarginAuto()
            ->build();
        $this->menues[]=$menu;

    }

//example of class passed
protected $menu=array(
        'title'=>'Landing Page Operations','items'=>[

            ['menu item' =>'Delete Landing HTML Page','method'=>'LandingPage__delete_landing_page'],
            ['menu item' =>'Create Landing Page','method'=>'LandingPage__create_landing_page']
]
    );
public function menu(){
        return $this->menu;
    }
`

And this is where I need the sub menus titles:

` public function open_menu() :void {
        

        $this->main_menu
            ->setTitle('SOME TITLE')
            //this goes inside a foreach for the array containing all the sub menus
            ->addSubMenuFromBuilder($this->menues[0]->title(),$this->menues[0])
            ->build()->open();
    }`

Sorry for the long reply. Is it clear?

**Comment by Lynesth** [comment]
It is 100% clear :)

I guess you can temporarily save the titles either as another array or as the key of your `$menues` array but I understand your point.

That would mean that we need to add a `getTitle()` public function to the CliMenu and either a `getMenuTitle()` or a `getMenu()` to the CliMenuBuilder.

I recall having a conversation on the subject with @AydinHassan so I'll wait for his comment before adding a PR.

**Comment by taytus** [comment]
Hello @AydinHassan. 

This is not a random property. This is not asking for: How many childs a menu has or something like that. 

The menu's title is one of the top level attributes we set up. I don't think is crazy to ask for an easy way to get that attribute back.

We can get almost all the styling related properties but we can't get menu title? 

All that being said, this is something I can (and already) solve. 

Totally cool if you don't want to write a getter for it, my only argument is that for tier one properties (like the title) the user should have an easier way to retrieve that property. That's all.

Love the tool, thanks for all your work. 👊🏼

**Comment by AydinHassan** [comment]
Hey @taytus - I just had a problem understanding the use-case - it seemed to me from the example given the problem could be resolved simply by re-organising some code. I'm happy to add code/features - but it needs a solid use-case before consideration. I didn't say it was crazy, but just because it's not crazy isn't justification in itself. I hope you understand my thought process. Glad you are enjoying the package!

**Comment by AydinHassan** [comment]
Closing this since the author solved the problem another way. Feel free to open more issues if you come across any other problems!
