### ISSUE TITLE
Self created new lines result in unexpected new lines in output

### ISSUE THREAD

**Issue by simonschaufi** [php-school/cli-menu#163]
## Source:
```php
$option = $this
    ->menu('Pizza menu:' . PHP_EOL . 'Name: Pizza by the slice' . PHP_EOL . 'Address: 12345 San-Francisco', [
        'Freshly baked' . PHP_EOL . 'muffins',
        'Freshly baked' . PHP_EOL . 'croissants',
        'Turnovers, crumb cake,' . PHP_EOL . 'cinnamon buns, scones'
 ])->open();
```

## Expected Output:

```
    Pizza menu:
    Name: Pizza by the slice
    Address: 12345 San-Francisco
    ----------------------------------------------------------------

    ● Freshly baked muffins
    ○ Freshly baked croissants
    ○ Turnovers, crumb cake, cinnamon buns, scones
    ○ Exit
```

## Real Output: 
```
    Pizza menu:
    Name: Pizza by the slice
    Address: 12345
    San-Francisco
    ----------------------------------------------------------------

    ● Freshly baked muffins
    ○ Freshly baked croissants
    ○ Turnovers, crumb cake, cinnamon buns, scones
    ○ Exit
```

I have no idea why there is an additional newline after the zip code. I have played around with str_pad but nothing helped.

Additionally it would also be great if newlines could work well in the items:

```
    Pizza menu:
    Name: Pizza by the slice
    Address: 12345
    San-Francisco
    ----------------------------------------------------------------

    ● Freshly baked
    muffins
    ○ Freshly baked
    croissants
    ○ Turnovers, crumb cake,
    cinnamon buns, scones
    ○ Exit
```
* The m from muffins is alligned with the dot but insted it should be alligned with the F.

**Comment by Lynesth** [comment]
Hello !

I suppose you are using @nunomaduro's implementation of CliMenu for Laravel which - I think - hasn't yet updated to CliMenu 3.0. Nevertheless, your example works perfectly with "vanilla" code:

```php
<?php

use PhpSchool\CliMenu\CliMenu;
use PhpSchool\CliMenu\Builder\CliMenuBuilder;

require_once(__DIR__ . '/../vendor/autoload.php');

$menu = (new CliMenuBuilder)
    ->setTitle('Pizza menu:' . PHP_EOL . 'Name: Pizza by the slice' . PHP_EOL . 'Address: 12345 San-Francisco')
    ->addItem('Freshly baked' . PHP_EOL . 'muffins', function() {})
    ->addItem('Freshly baked' . PHP_EOL . 'croissants', function() {})
    ->addItem('Turnovers, crumb cake,' . PHP_EOL . 'cinnamon buns, scones', function() {})
    ->build();

$menu->open();
```

![mintty_2018-05-22_09-05-24](https://user-images.githubusercontent.com/5318258/40332474-f0c5c8da-5d9f-11e8-99a5-34dbf7662d9e.png)

**Comment by simonschaufi** [comment]
Yes, I just noticed I'm using the old 2.x version of your cli-menu. I have upgraded now with some tweaks but experience more problems now than before.

When I manually set the margin the whole layout is broken for example. I use putty with an ubuntu homestead box.

I will play around more and see what exactly is broken.

**Comment by nunomaduro** [comment]
@Lynesth Yop. Didn't have time yet for that upgrade.

**Comment by AydinHassan** [comment]
@simonschaufi looks like the width is just too wide for the terminal window, try set it smaller.

**Comment by Lynesth** [comment]
@simonschaufi Just as Aydin said, the menu's width does not include the margin anymore in 3.0 so you need a terminal of at least the width + the left margin (the right margin is not printed).

The width of a menu is now comprised of the borders width (left and right), the padding (left and right) and then the rest is for the content. Think of it as `box-sizing: border-box` if you're familiar with CSS.

![firefox_2018-05-05_19-05-08](https://user-images.githubusercontent.com/5318258/39661165-f5d172a2-5098-11e8-998b-1a14bfd955e2.png)

**Comment by simonschaufi** [comment]
A default putty window is 80 chars wide. When I set the width to be static (to 78), then I don't get a "responsive" view any more with flexible/auto width. How do I make a frame with 1 margin and a border then with full width?

**Comment by AydinHassan** [comment]
I think you would have to calculate it yourself yes. Maybe we could add a `setWidthMax` or something that would set the width to the maximum value based on the margin. Happy for any PR's.

**Comment by simonschaufi** [comment]
What was the reason why you don't include the margin any more?

**Comment by AydinHassan** [comment]
There wasn't a reason that I know of - it was done as part of https://github.com/php-school/cli-menu/pull/103/files maybe @Lynesth has a reason.

**Comment by simonschaufi** [comment]
ok, since my initial issue is solved, this issue can be closed. Anything else is a feature request.
