### ISSUE TITLE
Line Breaks in confirm

### ISSUE THREAD

**Issue by TwinMist** [php-school/cli-menu#166]
How do you add line breaks in confirm?
ie.
confirm?
----------
option1
2
3
ok

**Comment by AydinHassan** [comment]
hi @andyrav do you mean how to display multiple options or just have a line break in the text?

In any case, neither is possible at this time, sorry!

**Comment by andyrav** [comment]
display multiple lines

**Comment by AydinHassan** [comment]
It's not possible. Feel free to send a PR!

**Comment by Lynesth** [comment]
You could use a submenu with static items and no exit button as a substitute.
Not the best way to do it I agree, but that's currently the only way I guess.

If you feel like it, send a PR ;)
