### ISSUE TITLE
Check if tput exists before casting the exec result to an int

### ISSUE THREAD

**Issue by gezzyramos** [php-school/cli-menu#169]
Hello, when calling the setWidth function it checks if the passed value is greater than the total width of the terminal, but in my case the maximum width of the terminal always returns zero, for some reason the getWidth function can not get the actual width of the terminal .

I suggest setting a default maximum value, if the getWidth function returns zero.

Screenshots

without changing
![terminal](https://user-images.githubusercontent.com/43446349/54133506-f56aa900-43f4-11e9-8b77-394b956659e1.jpg)

with change

File: MenuStyle.php
line 390: $width = ($this->terminal->getWidth() != 0) ? $this->terminal->getWidth() : 75 ;
![corrigido](https://user-images.githubusercontent.com/43446349/54133957-d0c30100-43f5-11e9-93e8-799255e1f17d.jpg)

**Comment by AydinHassan** [comment]
Hmm. Seems a bit hacky, we can certainly look at this but I'd rather figure out why `getWidth()` is returning 0. What does `put cols` return in your terminal? What terminal are you using? OS? Thanks!

**Comment by gezzyramos** [comment]
Of course, the ideal would be to know why `getWidth()` is returning 0.
`tput cols` return 213
Deepin's terminal, edition 15.9.1 Desktop

**Comment by AydinHassan** [comment]
Interesting. Could you try: `php -r "var_dump(exec('tput cols'));"` ?

And maybe also: `php -r "var_dump(function_exists('exec'));"`

**Comment by gezzyramos** [comment]
O problema está no meu ambiente, estou com a aplicação no docker e o sistema usado não possui o comando tput.

sendo assim a issue pode ser fechada.

Obrigado pela ajuda. :D

**Comment by gezzyramos** [comment]
The problem is in my environment.
I have the application in docker and the system used does not have the tput command.

so the issue can be closed. :D

Thank you for your help.

**Comment by AydinHassan** [comment]
Cool, glad we found it. Maybe we can add a better error message? Do you think it’s worth it?

Sent from my iPhone

On 11 Mar 2019, at 23:40, Gezzy Ramos <notifications@github.com<mailto:notifications@github.com>> wrote:


The problem is in my environment.
I have the application in docker and the system used does not have the tput command.

so the issue can be closed. :D

Thank you for your help.

**Comment by gezzyramos** [comment]
Of course, it would be good to inform when the system has not `tput` :)
