### ISSUE TITLE
building menu not all at once ?

### ISSUE THREAD

**Issue by vesper8** [php-school/cli-menu#170]
I would like to build up the menu slowly, using methods and classes since it's a big menu

I notice that while this works:

```
$itemCallable = function (CliMenu $menu) {
    echo $menu->getSelectedItem()->getText();
};

$menu = (new CliMenuBuilder)
    ->setTitle('Basic CLI Menu')
    ->addItem('First Item', $itemCallable)
    ->addItem('Second Item', $itemCallable)
    ->addItem('Third Item', $itemCallable)
    ->addLineBreak('-')
    ->setBorder(1, 2, 'yellow')
    ->setPadding(2, 4)
    ->setMarginAuto()
    ->build();

$menu->open();
```

this doesn't? 

```
$itemCallable = function (CliMenu $menu) {
    echo $menu->getSelectedItem()->getText();
};

$menu = (new CliMenuBuilder);
$menu->setTitle('Basic CLI Menu');
$menu->addItem('First Item', $itemCallable);
$menu->addItem('Second Item', $itemCallable);
$menu->addItem('Third Item', $itemCallable);
$menu->addLineBreak('-');
$menu->setBorder(1, 2, 'yellow');
$menu->setPadding(2, 4);
$menu->setMarginAuto();
$menu->build();

$menu->open();
```

How come? Shouldn't they both be the same?

**Comment by vesper8** [comment]
ahh.. it looks like the 2nd code sample works only if you chain together build and open:

works
```
$itemCallable = function (CliMenu $menu) {
    echo $menu->getSelectedItem()->getText();
};

$menu = (new CliMenuBuilder);
$menu->setTitle('Basic CLI Menu');
$menu->addItem('First Item', $itemCallable);
$menu->addItem('Second Item', $itemCallable);
$menu->addItem('Third Item', $itemCallable);
$menu->addLineBreak('-');
$menu->setBorder(1, 2, 'yellow');
$menu->setPadding(2, 4);
$menu->setMarginAuto();
$menu->build()->open();
```

**Comment by vesper8** [comment]
but then I found out that when doing it this way.. a bunch of things don't work

this won't work for example

```
        $itemCallable = function (CliMenu $menu) {
            echo $menu->getSelectedItem()->getText();
        };

        $menu = (new CliMenuBuilder);
        $menu->addItem('Third Item', $itemCallable);
        $menu->addLineBreak('-');

        $menu->addCustomControlMapping('t', $itemCallable);

        $menu->build()->open();
```

it gives an error
```
Call to undefined method PhpSchool\CliMenu\Builder\CliMenuBuilder::addCustomControlMapping()
```

When building the menu in a modular way like this, I also can't call ->close() or ->redraw()

Please advise @AydinHassan, I really need to be able to build the menu not all at once

**Comment by AydinHassan** [comment]
Well the menu is only created when you call build. Build returns the instance of the menu. You can call close on that and the other method.

The other methods you are calling are acting on the CliMenuBuilder. You only get an instance of CliMenu when you call build.

Try go through the docs again, it is all detailed there. Thanks.

Sent from my iPhone

On 1 Apr 2019, at 03:55, C-Bass <notifications@github.com<mailto:notifications@github.com>> wrote:


but then I found out that when doing it this way.. a bunch of things don't work

this won't work for example

        $itemCallable = function (CliMenu $menu) {
            echo $menu->getSelectedItem()->getText();
        };

        $menu = (new CliMenuBuilder);
        $menu->addItem('Third Item', $itemCallable);
        $menu->addLineBreak('-');

        $menu->addCustomControlMapping('t', $itemCallable);

        $menu->build()->open();


it gives an error

Call to undefined method PhpSchool\CliMenu\Builder\CliMenuBuilder::addCustomControlMapping()


When building the menu in a modular way like this, I also can't call ->close() or ->redraw()

Please advise @AydinHassan<https://github.com/AydinHassan>, I really need to be able to build the menu not all at once

**Comment by Lynesth** [comment]
Hey there @vesper8 

I didn't have time to check everything right now but I think your code example (the one that doesn't work from your first post) would work by changing:

`$menu->build();`
into
`$menu = $menu->build();`

Because what you previously have (your $menu) is a MenuBuilder, not a Menu, and it's actually the `build()` function that returns the actual Menu that you can `open()`

It's the same regarding your `addCustomControlMapping` issue, because that's a function the Menu has, not the MenuBuilder.

**Comment by vesper8** [comment]
@Lynesth you nailed it!! thanks!! that's just what it was!
