### ISSUE TITLE
text and number input should also implement same setValidator as password field?

### ISSUE THREAD

**Issue by vesper8** [php-school/cli-menu#173]
I know I could create my own custom inputs but I feel like the default inputs should have the same ability to set a custom validator as the password input.. I mean why not? If none is set then it will default to the current behaviour, and if the user wants to set a custom validator then he just has to provide a closure like in the password example

would you accept a PR for adding this?

**Comment by vesper8** [comment]
I also notice that many of the methods inside Number, Password and Text are duplicated

I see you use Input as a contract currently. Would you a PR that moves all these duplicated methods inside the implemented Input?

**Comment by AydinHassan** [comment]
Yeah I don't see why not for the validators. I don't care so much about introducing inheritance chains though - the code is not very complicated.

**Comment by AydinHassan** [comment]
@vesper8 do you plan on working on this or can I close?

**Comment by vesper8** [comment]
yes I was waiting for you to push the other stuff so I can get a fresh fork and add these changes. I'm already using them locally.. although I did add a bunch of inheritance.. I'm a bit OCD about duplicated code.. but I'll submit a PR that doesn't include all that and just adds the setValidator methods to the text/number classes. I'll do that now!
