### ISSUE TITLE
Set Width for Inputs

### ISSUE THREAD

**Issue by taytus** [php-school/cli-menu#178]
Hello!

I'm trying to set up the width of an input without luck.

Any idea how to achieve this?
```

$style = (new MenuStyle())
            ->setBg('yellow')
            ->setFg('black')
            ->setWidth('300');

 return function (phps_cliMenu $menu) use($style,$options){
            $result = $menu->askText($style)
                ->setPromptText($options['prompt_text'])
                ->setPlaceholderText($options['placeholder_text'])
                ->setValidationFailedText($options['validation_fail_text'])
                ->ask();

        };
```

**Comment by AydinHassan** [comment]
Hi @taytus this is not possible atm!

**Comment by taytus** [comment]
Cool, thank you @AydinHassan. I've found a super hacky workaround but hey... it works!
Sharing here just in case someone runs into the same problem:

```


```
function test($options, $width){
$spacer= str_repeat (" ", $width );

$result = $menu->askText()
                ->setPromptText($spacer.$options['prompt_text'].$spacer)
                ->setPlaceholderText($options['placeholder_text'])
                ->setValidationFailedText($options['validation_fail_text'])
                ->ask();
}

**Comment by AydinHassan** [comment]
Nice! feel free to send a PR adding the functionality if you want :)
