### ISSUE TITLE
stty: invalid argument ‘canon’

### ISSUE THREAD

**Issue by jtreminio** [php-school/cli-menu#218]
Commit f796a5ae8147896edb0988d782b082ef9708f26e introduced bug where `stty: invalid argument ‘canon’` is echoed on exiting.

```
stty: invalid argument ‘canon’
Try 'stty --help' for more information.
```

**Comment by AydinHassan** [comment]
Run `composer update` that dependency bump fixes the command.

**Comment by jtreminio** [comment]
Sure does, thanks!
