### ISSUE TITLE
Columns < 100 results in broken submenu layouts/colors

### ISSUE THREAD

**Issue by jtreminio** [php-school/cli-menu#219]
To show current size use `tput cols`

![Peek 2019-12-21 13-22](https://user-images.githubusercontent.com/589398/71312799-040ad580-23f5-11ea-928a-cd1ea5af62bc.gif)

Here it is with 100:

![Peek 2019-12-21 13-23](https://user-images.githubusercontent.com/589398/71312809-2866b200-23f5-11ea-829d-11ffb8529c3f.gif)

I am able to reproduce across several different terminal emulators.

**Comment by jtreminio** [comment]
I've gone back several tags and seems this problem has existed for some time... but I did not composer update on them, always using the latest `PhpSchool\Terminal` package.

**Comment by jtreminio** [comment]
The cause seems to be the `MenuStyle::$defaultStyleValues['width']` value.

If I set it to 80, and my columns are 99, the menu displays as expected.

If I set it to 80 and set cols size to 80, menu displays as expected.

Resetting to 100 reproduces bug.

**Comment by AydinHassan** [comment]
This is correct (expected behaviour). The default size of the menu is 100. So unless you change the width to a smaller value it will overlap.

You can grab the Terminal object and set the width based on the terminal size. 

https://github.com/php-school/cli-menu#width

**Comment by AydinHassan** [comment]
I guess we could treat the default the same as we do when manually setting a value larger than the terminal width.

**Comment by AydinHassan** [comment]
Actually. There is a bug, it's the default margin. Looks like it might not be taken into account when calculating the width.

**Comment by AydinHassan** [comment]
Replacing `\PhpSchool\CliMenu\MenuStyle::calculateContentWidth` with the below code fixes it. Breaks lots of tests though. I don't have time to fix it right now.

```php
/**
 * Calculate the contents width
 */
protected function calculateContentWidth() : void
{
    $this->contentWidth = $this->width
        - ($this->paddingLeftRight * 2)
        - ($this->borderRightWidth + $this->borderLeftWidth)
        - $this->margin;

    if ($this->contentWidth < 0) {
        $this->contentWidth = 0;
    }
}
```

**Comment by jtreminio** [comment]
While that fixes the broken column sizing for submenus, it does not fix passing the passing parent style to child because `hasChangedFromDefaults()` fails.

Running the initial test in a terminal with 95 cols `hasChangedFromDefaults` returns false because the parent's `width` is 95 but the default static width is still 100.

**Comment by jtreminio** [comment]
The following solves the issue:

```
diff --git a/src/MenuStyle.php b/src/MenuStyle.php
index 0bd0974..893f892 100644
--- a/src/MenuStyle.php
+++ b/src/MenuStyle.php
@@ -199,6 +199,8 @@ class MenuStyle
         'conceal'    => ['set' => 8, 'unset' => 28]
     ];
 
+    private static $widthOverridden = false;
+
     /**
      * Initialise style
      */
@@ -211,6 +213,10 @@ class MenuStyle
 
         $this->generateColoursSetCode();
 
+        if (!static::$widthOverridden && self::$defaultStyleValues['width'] !== $this->terminal->getWidth()) {
+            self::$defaultStyleValues['width'] = $this->terminal->getWidth();
+        }
+
         $this->setWidth(self::$defaultStyleValues['width']);
         $this->setPaddingTopBottom(self::$defaultStyleValues['paddingTopBottom']);
         $this->setPaddingLeftRight(self::$defaultStyleValues['paddingLeftRight']);
@@ -317,7 +323,8 @@ class MenuStyle
     {
         $this->contentWidth = $this->width
             - ($this->paddingLeftRight * 2)
-            - ($this->borderRightWidth + $this->borderLeftWidth);
+            - ($this->borderRightWidth + $this->borderLeftWidth)
+            - $this->margin;
 
         if ($this->contentWidth < 0) {
             $this->contentWidth = 0;
```

It includes your patch as well as updating the default width the first time the class is instantiated. Since it's a static the change reflects.

**Comment by AydinHassan** [comment]
There is another bug as well with margin auto. Need to look in to that more but I  think `calculateContentWidth()` into `setMarginAuto()` might help.
