### ISSUE TITLE
Composer version differents to github repo

### ISSUE THREAD

**Issue by VladReshet** [php-school/cli-menu#228]
Hi,

when you install this package via composer, you get non-current version, which has no checkboxes. Last composer version is dated 8 month ago. Is that OK?

**Comment by AydinHassan** [comment]
hey @VladReshet yeah it's not released yet, there are some things to finish off first.

**Comment by AydinHassan** [comment]
You can install the master branch though and play with the new features: `composer require php-school/cli-menu:dev-master`

**Comment by VladReshet** [comment]
Got it, thanks! 

Just out of curiosity - is there an estimated date of release of these features?

**Comment by AydinHassan** [comment]
Unfortunately not, whenever I find some time and have a brainwave on how to solve a few issues 🤔

**Comment by VladReshet** [comment]
Got it. I hope you will have a time, because your lib is **really cool**! Thanks!

**Comment by AydinHassan** [comment]
hey @VladReshet will probably release 4.0.0 this week sometime :)

**Comment by VladReshet** [comment]
Wow, great! :)

**Comment by AydinHassan** [comment]
@VladReshet tagged 4.0.0 now 😃

**Comment by VladReshet** [comment]
Awesome, thanks!)

**Comment by AydinHassan** [comment]
If you send a PR we can add your integration to the readme at the bottom :)

**Comment by VladReshet** [comment]
At first sight my integration looks to be similar to this one 
![image](https://user-images.githubusercontent.com/7568590/74825548-cfdb6480-5312-11ea-80de-e2d14a50f9fe.png)
but in fact they have really different functionality.

Anyway, i will send you PR today, and the decision is yours :) Thanks
