### ISSUE TITLE
Don't append two \n in CliMenu::draw()

### ISSUE THREAD

**Issue by jtreminio** [php-school/cli-menu#229]
Howdy.

`draw()` calls `newLine()` twice: https://github.com/php-school/cli-menu/blob/master/src/CliMenu.php#L530

If we're trying to build an app that fits within "standard" 24x80 the new lines take up quite a bit of space:

![image](https://user-images.githubusercontent.com/589398/74111472-56958200-4b5a-11ea-8d51-730c6719571b.png)

vs not including them:

![image](https://user-images.githubusercontent.com/589398/74111484-64e39e00-4b5a-11ea-9ff8-4a02adec4759.png)

There's no option to remove this. Thoughts on removing or adding a default-on flag that can be disabled?

**Comment by AydinHassan** [comment]
I don't see why not, would you do it for both top and bottom, or just bottom?

**Comment by AydinHassan** [comment]
@jtreminio planning on releasing 4.0.0 in the next couple of days if there's anything you want to add :)
