### ISSUE TITLE
Auto detect current background 

### ISSUE THREAD

**Issue by mikeerickson** [php-school/cli-menu#233]
Looking for some advise on setting foreground / background colors based on current terminal settings. 

Ideally, just do some simple inversion would suffice.   

What have you all done under these conditions?

**Comment by AydinHassan** [comment]
Hey, sorry I’ve never come across this problem so I can’t really help. Did you manage to find any information?

**Comment by mikeerickson** [comment]
Nope, I could not find a working solution

**Comment by AydinHassan** [comment]
@mikeerickson  If you come up with something in the future, that would be a pretty cool feature!

**Comment by mikeymike** [comment]
You can set the background and foreground colours, so I think the worst case scenario would be the background is the same as the terminal background. 

All scenarios I think are fine as long as you set your background and foreground with enough contrast it should always be readable 

(This doesn't of course cover the cases where the user has customised their terminal colours unfortunately)
