### ISSUE TITLE
Using escape key as CustomControlMapping

### ISSUE THREAD

**Issue by taytus** [php-school/cli-menu#239]
Hello everyone 👋🏻

is this possible? I've tried: `$menu->addCustomControlMapping('ESC', $exit);` and other variations such as "esc", "escape" and 'ESCAPE" and none seems to work.

Thank you!

**Comment by AydinHassan** [comment]
Hello,

Unfortunately there is not a way to do this at the minute, sounds like a welcome feature to me though!
