### ISSUE TITLE
struggling to re-generate sub-menu dynamically

### ISSUE THREAD

**Issue by vesper8** [php-school/cli-menu#244]
I made a CLI menu for quick-saving and quick-loading inside of a game.

When I run the quick-save I'm prompted for a text input, and then a new file is generated.

Then when I choose the quick-load command, it opens a sub-menu and iterates over each file inside of a folder and creates sub-menu items. Upon clicking one then that file is copied somewhere.

My issue is that my list of "loadable" files is only built once when I first run the menu.

I've tried many things with the redraw() method but I can't seem to get that sub-menu to be generated on the fly, each time I enter the "Quick Load" menu.

Is it possible to regenerate the submenu items each time I select it from the top menu?

Here's a working sample of what I'm trying to achieve

```

        $menu = (new \PhpSchool\CliMenu\Builder\CliMenuBuilder);
        $menu->setTitle('Quick Menu');

        $commands = function (\PhpSchool\CliMenu\Builder\CliMenuBuilder $subMenu) {
            $subMenu->setTitle('Commands');

            $itemCallable = function (\PhpSchool\CliMenu\CliMenu $menu) {
                $result = $menu->askText()
                    ->setPromptText('Enter Save Name')
                    ->ask();

                $args['filename'] = $result->fetch();

                \Artisan::call('quick:save', $args);
            };

            $subMenu->addItem('Quick Save', $itemCallable);

            $quickLoadMenu = function (\PhpSchool\CliMenu\Builder\CliMenuBuilder $subMenu) {
                $subMenu->setTitle('Quick Load');

                $path = '/path/to/files';
                $backupFolder = sprintf('%s/backup-saves', $path);

                $backupSaves = \File::files($backupFolder);

                foreach ($backupSaves as $backupSave) {
                    $subMenu->addItem($backupSave->getFileName(), function () use ($backupSave) {
                        $args['filename'] = $backupSave->getFileName();
                        \Artisan::call('quick:load', $args);
                    });
                }
            };

            $subMenu->addSubMenu('Quick Load', $quickLoadMenu);
        };

        $menu->addSubMenu('Run [C]ommands', $commands);

        $menu = $menu->build();

        $menu->open();
```

Many thanks!

**Comment by AydinHassan** [comment]
Hello, unfortunately that is not currently possible. You would have to customise a lot of the components to make that work. 

I'd probably start with creating a new menu item and customise the select action: https://github.com/php-school/cli-menu/blob/7ba829ff6f6fa7c79b8677371890ead035214fe3/src/MenuItem/MenuMenuItem.php#L79

This is what is triggered when you "select" the item. Note that you will need to manually construct the `CliMenu` instance. You might also need to replicate some of the code in this method too: https://github.com/php-school/cli-menu/blob/92dd003b17828ba1332dda0f715dbeb03ffb278c/src/Builder/CliMenuBuilder.php#L207

**Comment by vesper8** [comment]
Thank you for the help! Sounds a bit daunting but at least you think it is possible? It would be a nice addition to cli-menu IMO. I may give it a crack

**Comment by vesper8** [comment]
@AydinHassan Could you perhaps say a few more words though about why this isn't currently possible, and what would need to change (what I would need to add) in order to make it possible?

Is it not possible only because I am dealing with a sub-menu?

**Comment by AydinHassan** [comment]
@vesper8 each menu type (https://github.com/php-school/cli-menu/tree/master/src/MenuItem) has a method `getSelectAction` - in the case of normal selectable items, you provide the callable to be executed. In the case of submenu's the action is not customisable - it is closure which opens the menu, see my first link in the previous comment.

We could allow to specify a custom callback for when a submenu is selected but we would need to flesh out the order in which this should happen, should the user function be executed before or after the sub menu is opened? Should the user function just be passed the default action and they can just run that as and when they want?

Overall I'm not entirely sure we need this as a feature, I'd like to see an implementation before I decide if the complexity is worth it. I appreciate it might not be worth your effort in that case, so that's your call 😃

**Comment by vesper8** [comment]
Ok thanks for the clarification @AydinHassan 

Before I decide whether I want to give this a shot, can you see an alternative way of achieving what I want to do with another type of menu item?

For me it really doesn't have to be a sub-menu.. The desired outcome is that upon clicking a menu item, I am given a list of freshly-generated options, and upon clicking any of those options, an action is immediately executed.

Is there a way to achieve this right now?

**Comment by AydinHassan** [comment]
@vesper8 no there is no other way
