### ISSUE TITLE
Menu Dialog

### ISSUE THREAD

**Issue by ccsliinc** [php-school/cli-menu#247]
Looking through the code, the confirm dialog is not actually a confirmation. It has no return value, am i missing something or the way it currently is just another layer in which a user cannot back out? It seems like there is nothing I can do with a dialog other than click enter. You cant even escape out.

I am just asking to know if there is an alternative.

**Comment by ccsliinc** [comment]
I was just trying to figure out if the user did not want to go through with the action what would they do. Even something as simple as hitting the escape key would allow them to exit the process. The only way I see it’s possible right now is if they actually exit the whole process itself. So for example if it was a confirm deletion dialogue and they accidentally hit it, then they have no way of backing out.

**Comment by AydinHassan** [comment]
Fixed with #248

**Comment by ccsliinc** [comment]
Is there any way you can add a point release to this PR. I use this but it's a requirement for another component. I'd like it to pull this release.

**Comment by ccsliinc** [comment]
Is there any way you can add a point release to this PR. I use this but it's a requirement for another component. I'd like it to pull this release.

**Comment by AydinHassan** [comment]
@ccsliinc [4.2.0](https://github.com/php-school/cli-menu/releases/tag/4.2.0)

**Comment by ccsliinc** [comment]
@AydinHassan Thank you.
