### ISSUE TITLE
Checked checkbox

### ISSUE THREAD

**Issue by loranger** [php-school/cli-menu#256]
Hi,

I cannot figure out how I can pre-check a checkbox when building a menu.
Is there a way to toggle some checkboxes on instanciation ?

**Comment by AydinHassan** [comment]
You can construct an instance of `PhpSchool\CliMenu\Builder\CheckboxItem` manually, call `toggle` on it and then add it to the builder with `addMenuItem`

**Comment by AydinHassan** [comment]
Feel free to reopen if you have any more questions

**Comment by loranger** [comment]
Ok, no shorthand for checkbox, got it.
Thanks @AydinHassan
