### ISSUE TITLE
Windows compatibility: replace posix_isatty() with stream_isatty()

### ISSUE THREAD

**Issue by underdpt** [php-school/cli-menu#257]
Hello,

Giving it another try to check if there's a way to make this package windows compatible, i found [stream_isatty()](https://www.php.net/manual/en/function.stream-isatty.php) which is described on php documentation as a `posix_isatty()` replacement, and is windows compatible.

What do you think?

**Comment by mikeymike** [comment]
Hey @underdpt 

Sounds promising, I'm not 100% sure what else might need refactoring to support windows but I'd be interested to see if that gets over any initial hurdles. I have little to no experience with windows around this area so would welcome any assistance, prototyping etc

**Comment by AydinHassan** [comment]
Also, looks like that function is only available in PHP 7.2, currently we support 7.1. I'm happy to drop support for 7.1 though. But as @mikeymike says, I don't think that will be last issue. In fact, we probably added that because we couldn't get it to work on windows.

**Comment by dverkauf** [comment]
Any news about Windows support?

**Comment by AydinHassan** [comment]
@dverkauf we tried with windows before and didn't make any progress so it's not a priority for us, but we are of course happy to accept pr's!
