### ISSUE TITLE
Menu items and cp1251

### ISSUE THREAD

**Issue by simonovich** [php-school/cli-menu#258]
Hi!
My terminal works with Windows-1251 encoding. Everything looks fine as long as I don't use Cyrillic characters.

#### Problem:
- Menu items go out of window
[please, see the screenshot](https://yadi.sk/i/0gmtAeEV1vM3tw)

#### For reproduce

Slightly modified example code:
```php
<?php
declare(strict_types=1);

use PhpSchool\CliMenu\CliMenu;
use PhpSchool\CliMenu\Builder\CliMenuBuilder;
use PhpSchool\CliMenu\Style\SelectableStyle;

require_once(__DIR__ . '/../vendor/autoload.php');

$itemCallable = function (CliMenu $menu) {
    echo $menu->getSelectedItem()->getText();
};

$menu = (new CliMenuBuilder)
    ->modifySelectableStyle(function (SelectableStyle $style) {
        $style->setSelectedMarker('')
            // disable unselected marker
            ->setUnselectedMarker('');
    })
    ->setTitle('Basic CLI Menu') // pass
    ->addItem(mb_convert_encoding("Первый пункт", "windows-1251", "utf-8"), $itemCallable) // fail
    ->addItem('Second Item', $itemCallable) // pass
    ->addItem(mb_convert_encoding("Third Item", "windows-1251", "utf-8"), $itemCallable) // pass
    ->setBorder(1, 2, '36')
    ->setMarginAuto()
    ->addLineBreak('-')
    ->build();

$menu->open();
```

#### Expected
- All lines with Cyrillic characters in cp1251 encoding remain within the window.

===
Ubuntu 22.04 LTS
PHP 7.4

**Comment by AydinHassan** [comment]
Thanks for the report. I can confirm it looks broken. Do you have any idea how to fix it?

**Comment by simonovich** [comment]
I found the mb_strlen() call in the drawMenuItem() function and it gave me a solution to the problem.

It is necessary to specify php internal encoding before creating the menu:
```php
require_once(__DIR__ . '/../vendor/autoload.php');

mb_internal_encoding('cp1251'); // the fix

$itemCallable = function (CliMenu $menu) {
    echo $menu->getSelectedItem()->getText();
};
```

I believe this is useful information for anyone using non-unicode menus.

**Comment by AydinHassan** [comment]
Great - thanks for the solution!

Sent from my iPhone

On 14 Jul 2022, at 14:21, simonovich ***@***.***> wrote:

﻿

I found the mb_strlen() call in the drawMenuItem() function and it gave me a solution to the problem.

It is necessary to specify php internal encoding before creating the menu:

require_once(__DIR__ . '/../vendor/autoload.php');

mb_internal_encoding('cp1251'); // the fix

$itemCallable = function (CliMenu $menu) {
    echo $menu->getSelectedItem()->getText();
};

I believe this is useful information for anyone using non-unicode menus.
