### ISSUE TITLE
setPromptText - multiline support

### ISSUE THREAD

**Issue by simonovich** [php-school/cli-menu#259]
Can you please suggest how to make multiline text for promt?

The example below breaks the menu:
```php
$itemCallable = function (CliMenu $menu) {
    $result = $menu->askText()
        ->setPromptText("Text line 1\nText line 2\nText line 3")
        ->setPlaceholderText('')
        ->ask();

    var_dump($result->fetch());
};
```
![Basic.php](https://downloader.disk.yandex.ru/preview/05ca4043f59f327f70da153fd46aee38dbe3c30be8d73fd683f0cf9bc7ac43c8/62d19c9e/fuUYa2cKTmx4zysHAQY-qZgdtnl3CtGZtlbzHElRKA_sy9VznZjtkJXyzSqtSeKDpqUAEK5gjlbGUvOWe1_3yA%3D%3D?uid=0&filename=2022-07-15_15-55-21.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&owner_uid=0&tknv=v2&size=2048x2048)

**Comment by AydinHassan** [comment]
It appears it's not handled/supported

**Comment by AydinHassan** [comment]
We will happily accept PR's but I don't imagine the maintainers will be working on it in the foreseeable future.

**Comment by simonovich** [comment]
Es tut mir so leid )

**Comment by AydinHassan** [comment]
Happy to accept a pr to add this, will close this issue for now though :)
