### ISSUE TITLE
PHPStorm - How to debug

### ISSUE THREAD

**Issue by simonovich** [php-school/cli-menu#261]
Traditionally, this project is debugged using the var_dump() function.
If we use xdebug we get an error.

Error reason: The program cannot get terminal parameters from the PHPStorm environment.

I propose a little hack:
```php
diff --git a/src/UnixTerminal.php b/src/UnixTerminal.php
index 879b1a7..2fdc248 100644
--- a/src/UnixTerminal.php
+++ b/src/UnixTerminal.php
@@ -71,12 +71,14 @@ class UnixTerminal implements Terminal
 
     public function getWidth() : int
     {
-        return $this->width ?: $this->width = (int) exec('tput cols');
+        //return $this->width ?: $this->width = (int) exec('tput cols');
+        return 33; // your terminal width
     }
 
     public function getHeight() : int
     {
-        return $this->height ?: $this->height = (int) exec('tput lines');
+        //return $this->height ?: $this->height = (int) exec('tput lines');
+        return 17; // your terminal height
     }
 
     public function getColourSupport() : int
@@ -166,7 +168,8 @@ class UnixTerminal implements Terminal
      */
     public function isInteractive() : bool
     {
-        return $this->input->isInteractive() && $this->output->isInteractive();
+        //return $this->input->isInteractive() && $this->output->isInteractive();
+        return true;
     }
 
     /**
```

Now you can work with the xdebug debugger, set breakpoints, and so on!

**Comment by mikeymike** [comment]
Hey @simonovich thanks for opening a discussion about this... you're right this isn't immediately obvious how to run with xdebug. 

We could supply an implementation of the Terminal interface that is purely for debugging, we could also detect a debugging environment and construct it with that terminal by default 🤔 

Hopefully, I can get some time to look at this in more detail soon

**Comment by ohot** [comment]
I've got the same issue with NetBeans/xdebug.

I don't manage to make the little hack from [simonovich](https://github.com/simonovich) to run properly.

**Comment by AydinHassan** [comment]
IMO the best way to debug is to listen for debug connections in PHPStorm and run cli-menu like so: `XDEBUG_SESSION=1 php examples/basic.php`. That is assuming you are using Xdebug 3.
