### ISSUE TITLE
Missing import

### ISSUE THREAD

**Issue by bozhinov** [php-school/cli-menu#269]
https://github.com/php-school/cli-menu/blob/70b73ee9104f0dda7d52fa0de73962e0eeaaf89b/src/CliMenu.php#L27

Hello,

there is no reference here to ArrayUtils.php
functions collect and each not found

PHP8.2 x64 FreeBSD

Momchil

**Comment by AydinHassan** [comment]
The functions are autoloaded in `composer.json` https://github.com/php-school/cli-menu/blob/master/composer.json#L33

**Comment by bozhinov** [comment]
yeah, missed that one. sorry

**Comment by AydinHassan** [comment]
No problem :)
