### ISSUE TITLE
Disable appveyor

### ISSUE THREAD

**Issue by AydinHassan** [php-school/cli-menu#28]
yo @mikeymike can you disable appveyor for PR's? I think you signed up with your GitHub so I don't have access. It's pretty annoying on PR's as they never pass anyway until we support Windows  :smile:

**Comment by mikeymike** [comment]
No problem, I've set it to build tags only. Hopefully that will do the
trick 😎

**Comment by AydinHassan** [comment]
Nice one :smile:
