### ISSUE TITLE
Possibilities

### ISSUE THREAD

**Issue by triplekdev** [php-school/cli-menu#30]
Hey, this is cool start.. but, any plans to just convert or create new library when Forms: Input, Combo Box, Check Box? hehe! just saying.. this is a great installer and a CLI app to begin with.

**Comment by AydinHassan** [comment]
We don't really have plans for that. I think other libraries have that covered and we want to keep this small and simple. If you have any more specific ideas or plans then feel free to jump on slack or open an issue/pr but I'm going to close this for now.
