### ISSUE TITLE
Add ability to use own Item classes

### ISSUE THREAD

**Issue by PhillippOhlandt** [php-school/cli-menu#34]
Hey,

I created my own Menu Item class in order to have key/values for my options. But I can't add it to the menu because the `addMenuItem` method is private.

I also can't extend the `CliMenuBuilder` class to add my own method that adds my Items because the `$menuItems` property is private too. 

Would be cool if the `addMenuItem` method would be public or the `$menuItems` property protected.

Is that a problem for you?

**Comment by AydinHassan** [comment]
My initial reaction is that it seems pretty strange that `addMenuItem` is private, so I'd say it's okay to make it public. @mikeymike do you remember the reason why it's not or was it just an oversight?

**Comment by mikeymike** [comment]
Yeah complete oversight ... I think we built this with the intention of each menu item type having its own method to add them, obviously this prevents custom menu items 

I'm think we should have this public ... From a brief look I can't see any reason why not anyway 👍

**Comment by AydinHassan** [comment]
@PhillippOhlandt fixed in #36

**Comment by PhillippOhlandt** [comment]
Awesome :)
