### ISSUE TITLE
Option to not clear the terminal window

### ISSUE THREAD

**Issue by PhillippOhlandt** [php-school/cli-menu#35]
Hey,

right now when you open a menu, the window will get cleared and shows only the menu. That's ok for me and I can work with that but I prefer to not clear the window. 

An option on the menu builder to turn it off would be nice.

**Comment by mikeymike** [comment]
hey @PhillippOhlandt thanks for the feedback, I think this would be very difficult to implement as each movement has to redraw the menu. We'd have to somehow keep track of which point of the screen needs to be redrawn rather than redrawing everything which I can only imagine will be pretty difficult. 

I can take a look into this a bit more over the weekend, but I suspect it would be a lot of changes.

**Comment by PhillippOhlandt** [comment]
It's ok when it's too much work. It's just a nice to have feature. I work with symfony/console and have some realtime data in an ascii table which will be redrawn every second. There I just have to know how many lines my table has, so I can reset the cursor.

For example, when I reset the cursor for 5 lines to redraw the table:
```
$output->write(sprintf("\r\033[%dA", 5));
```

Not sure if yours work the same way.

**Comment by mikeymike** [comment]
@PhillippOhlandt good idea!, we'd need to figure out how many lines the menu is taking up if we took that approach. Would probably be a lot easier than what I mentioned before though

**Comment by PhillippOhlandt** [comment]
You can also save the current cursor position and get back to it after. Here is some example code:
```
$output->write("\033[s");
$output->writeln("foo");
$output->writeln("foo");
$output->writeln("foo");
$output->writeln("foo");

sleep(2);

$output->write("\033[u");
```

Problem is, that (at least with text) the text won't be deleted. The result is:
![](https://infinit.io/_/3fCPsSZ.png)

I'll try to find a solution.

**Comment by PhillippOhlandt** [comment]
Found it!

`$output->write("\033[J");` clears everything after the cursor until the end of screen.

**Comment by mikeymike** [comment]
@PhillippOhlandt that looks really promising nice work man!

Do you want to try and write a PR for this ? I can take a look at doing it over the weekend but I'd love for you to get a contribution on the board, you have pretty much found the solution after all :smile:

**Comment by PhillippOhlandt** [comment]
I can try to get it running locally, but I can't promise it :D

**Comment by PhillippOhlandt** [comment]
Ok, the code to render that thing is a bit more complicated than I thought :D I have no problem if you want to do that, you know the codebase much better than me :)

**Comment by mikeymike** [comment]
No worries, I'll take a look at the weekend hopefully have PR up soon 👍😎

**Comment by mikeymike** [comment]
@PhillippOhlandt I've got this working on a [new branch ](https://github.com/php-school/cli-menu/tree/feature/no-clear-option) ... Noticed that this doesn't seem to work on Windows though using ConEmu + Cygwin :disappointed: 

I'm going to continue looking into it but thought I'd give you an update on progress :+1:

**Comment by PhillippOhlandt** [comment]
@mikeymike yeah I saw the branch already. Will try it tomorrow. :)

**Comment by PhillippOhlandt** [comment]
Hey, I just tested that. Works great! Do you know if it's possible to remove the menu after an option was selected?

**Comment by mikeymike** [comment]
Awesome! :+1: 

This would be handled within the callback used on the items. Take a quick look at @AydinHassan's [example](https://github.com/php-school/cli-menu/issues/33) and you'll notice he put the `$menu->close()` in the callable.

**Comment by PhillippOhlandt** [comment]
@mikeymike I do the same:

```
$callable = function (CliMenu $menu) {
            $this->selectedOption = $menu->getSelectedItem();
            $menu->close();
        };
```

**Comment by PhillippOhlandt** [comment]
I also found a bug. The menu will be redrawn when you are at the bottom of the console. See:
http://recordit.co/flHcbf7Uv4

**Comment by mikeymike** [comment]
@PhillippOhlandt nice spot, I'm not sure how we're going to resolve that issue, I can imagine it also causes issues when the user scrolls the terminal windows slightly ? 

I've been ill the past couple days so not had chance to look at this properly. Thanks for the feedback though 👍

**Comment by PhillippOhlandt** [comment]
No problem :)

**Comment by AydinHassan** [comment]
Going to close this for now, feel free to re-open if interest arises!
