### ISSUE TITLE
What about Hoa\Console

### ISSUE THREAD

**Issue by Hywan** [php-school/cli-menu#48]
Hello :-),

I wonder if you have ever considered using [the `Hoa\Console` library](https://github.com/hoaproject/Console), especially for the `Cursor`, `Window` and `Readline` feature?

You will gain more statibility on more terminals since it is based on tput.

You might be interested by this blog post to understand what I am talking about, https://mnt.io/P/2015-01-04_Control_the_terminal_the_right_way.html.

Regards.

**Comment by AydinHassan** [comment]
Hi, thanks for the heads up, it sounds interesting. Probably would be a lot of work so I don't think it will happen soon, but it would be nice to depend on this more stable code and remove some of our own.

**Comment by Hywan** [comment]
If you are interesting, we can help you probably. Just ping us 😄.
