### ISSUE TITLE
I get "not a valid TTY"

### ISSUE THREAD

**Issue by sergiokessler** [php-school/cli-menu#51]
PHP Fatal error:  Uncaught PhpSchool\CliMenu\Exception\InvalidTerminalException: Terminal "" is not a valid TTY
on windows 10 cmd  :-)

**Comment by AydinHassan** [comment]
Hi - unfortunately we have dropped support for windows. It is just missing features that we need. I thought it might work on Windows 10, but obviously not. Not of the maintainers have windows machines so unless some one can help out this probably isn't going to work on Windows for a while.

I have just recently pushed up a commit which requires ext-posix so installations should be blocked on windows when we release that, so at least you get some feedback.

Sorry about that - I'm going to close this for now - feel free to still comment and discuss and maybe someone will come in the future and solve this for us.
