### ISSUE TITLE
Prompt Dialogue

### ISSUE THREAD

**Issue by xduh** [php-school/cli-menu#58]
Hi.

I wonder if was good feature, having a prompt dialogue box to get data from user. What you think?

**Comment by AydinHassan** [comment]
Sounds cool to me! are you thinking of taking a crack at it?

**Comment by xduh** [comment]
Absolutely

**Comment by AydinHassan** [comment]
Let us know if youmaking any progress here 😀 Closing the issue for now.

**Comment by M0S4YSH3LL0** [comment]
Any progress yet?
