### ISSUE TITLE
Windows...

### ISSUE THREAD

**Issue by mikeymike** [php-school/cli-menu#6]

**Comment by wolfy-j** [comment]
What about supporting https://en.wikipedia.org/wiki/ConEmu (Win)? So far it works perfectly with Symfony Console, colorization and etc. I don't think there is any good chance to support native windows shell soon.

**Comment by mikeymike** [comment]
Your right, we don't expect Windows to come out with full support for the standard escape sequences. But @AydinHassan has made some amazing progress getting [Ansicon](https://github.com/adoxa/ansicon) bundled and we will be potentially looking to breakout our own Colour lib at some point so not only will it work in all these components but others can benefit too :smile:  

Also unfortunately we're limited to testing Windows as we all run OS X but (although untested) if there's a shell for Windows that supports the standard escape sequences then it should work... well maybe (anyone's welcome to test and feedback what support it has even if limited)
