### ISSUE TITLE
Use cli-menu via ssh on a Debian 7 server

### ISSUE THREAD

**Issue by supertorti** [php-school/cli-menu#60]
Hi,

im trying to use the cli-menu on a Debian 7 Server with PHP 5.6  via ssh.

Script works perfectly on my local mac, but when im trying to start the menu script from remote server, there comes just nothing. Not a even an error or something.

Any idea about that?

Greetings from germany

**Comment by AydinHassan** [comment]
Hi, 

That's very strange - could you maybe post a screenshot or something? Or maybe if you could re-produce with in a VM so we could debug?

Also - how is your error reporting on the server? Does it have the posix extension installed?

**Comment by mikeymike** [comment]
hey @supertorti can you check to see if error reporting is enabled on the PHP configuration file, also it might be being output to a log file which would be specified in the configuration file as well. 

You can run `php --ini` to find the loaded configuration file 👍

**Comment by supertorti** [comment]
Hi and thanks for your fast response!

1. Is Posix extension installed? -> Yes
2. Error are shown and logged -> Yes (I provoke a few to test it)

But still no errors..!? Is there a debug modus or something, to get a little information?

**Comment by supertorti** [comment]
Ok, the problem is definitely in my script. When i use your example, it works like a charm!

Thanks verry much for your help!

**Comment by AydinHassan** [comment]
No problem - glad it sort of works :D
