### ISSUE TITLE
 Add `separator` line support in options

### ISSUE THREAD

**Issue by mikeerickson** [php-school/cli-menu#70]
Please see extended description here where it was first discovered

https://github.com/nunomaduro/laravel-console-menu/issues/7

**Comment by AydinHassan** [comment]
Hi - I'm not sure there is anything to solve here in this repository - this seems to be due to the way items are added to the menu in the Laravel wrapper.

The API to add an item and a line break is:

```
$menu = $menuBuilder
    ->addItem('Third Item', $itemCallable)
    ->addLineBreak('-')
    ->build();
```

**Comment by mikeerickson** [comment]
OK, as mentioned, I have opened a ticket there as well. I will have a closer look
