### ISSUE TITLE
If option item text is greater than width, it has syntax error

### ISSUE THREAD

**Issue by mikeerickson** [php-school/cli-menu#71]
Please see extended description here where it was first discovered

https://github.com/nunomaduro/laravel-console-menu/issues/8

**Comment by AydinHassan** [comment]
This definitely looks like something we should fix 😄

**Comment by mikeerickson** [comment]
Alrighty, I will get a PR submitted :)

**Comment by AydinHassan** [comment]
Fixed in #112
