### ISSUE TITLE
Contribution Offer

### ISSUE THREAD

**Issue by mikeerickson** [php-school/cli-menu#72]
If you are keen to accept contribution PRs, I would be happy to provide fixes for the two items I reported to get started

Add `separator` line support in options - https://github.com/php-school/cli-menu/issues/70
If option item text is greater than width, it has syntax error - https://github.com/php-school/cli-menu/issues/71

**Comment by AydinHassan** [comment]
Please feel free 😄 - try to add tests where you can, and do ask if there is anything you need help with!
