### ISSUE TITLE
ERRO INSTALlATION

### ISSUE THREAD

**Issue by JohnatanT** [php-school/cli-menu#75]
Problem 1
    - Installation request for php-school/cli-menu ^2.1 -> satisfiable by php-school/cli-menu[2.1.0].
    - php-school/cli-menu 2.1.0 requires ext-posix * -> the requested PHP extension posix is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by mikeerickson** [comment]
@JohnatanT Have you enabled `posix` on your system as per the recommendation

**Comment by AydinHassan** [comment]
Hi @JohnatanT - @mikeerickson is correct. `cli-menu` needs `ext-posix` to function. It looks like you are running Windows where `ext-posix` is not available and therefore will not work. You can either run via `docker` or via a combination of Cygwin + ConEmu.

**Comment by JohnatanT** [comment]
Thanks, would it work using Vagrant?

**Comment by AydinHassan** [comment]
Yeah but you still need to use ConEmu I think due to the way Windows and ANSI escape sequences work (or don't)  @mikeymike correct me if I'm wrong please :)

**Comment by mikeymike** [comment]
IIRC ConEmu will essentially correctly output all ANSI escape sequences where the default Windows Command Line doesn't. Details on ANSI codes with ConEmu can be [found here...](https://conemu.github.io/en/AnsiEscapeCodes.html)

**Comment by JohnatanT** [comment]
Thank you all for your help
😄

**Comment by AydinHassan** [comment]
@JohnatanT you are welcome! I will close this now but feel free to reopen or create a new issue if you have any problems.
