### ISSUE TITLE
No cursor in terminal when exiting

### ISSUE THREAD

**Issue by Lynesth** [php-school/cli-menu#90]
So I made #89 but it doesn't work as intended.

I think it's the restoreOriginalConfiguration which doesn't work in my case.
Adding enableCursor and enableEchoBack after the stty exec call in restoreOriginalConfiguration (inside php-school/terminal/UnixTerminal.php) makes it work.

(I need to add both, because just adding enableCursor gives the cursor back but removes the echo !!!)

Not sure if real issue or just specific case.

**Comment by AydinHassan** [comment]
Yeah I've noticed this also - I'm going to take a closer look, because the restore should work. It just takes a snapshot of the current config and applies that back, we must be doing something weird somewhere.

**Comment by Lynesth** [comment]
I checked directly in the terminal, echoing `\033[25l` or executing `tput civis` doesn't change the output of `stty -g`.

**Comment by AydinHassan** [comment]
ah yeah, so we definitely need to enable the cursor in `tearDownTerminal` but echo back should be handled by the stty restore. Maybe something weird is going on with the  `exec` call. Looks like we are using the return value which is only the last line of input.

**Comment by Lynesth** [comment]
The echo back is correctly handled yes, nevermind that I don't know what went wrong.
Reenabling the cursor in restoreOriginalConfiguration does the trick (not in tearDownTerminal or it wouldn't be restored on terminal __destruct).
