### ISSUE TITLE
Need some consistent way to select menu items

### ISSUE THREAD

**Issue by Lynesth** [php-school/cli-menu#91]
We currently have `$CliMenu->getItems()` which returns items indexed by position.
So let's say I need the 4th item in the menu, I need to use `$CliMenu->getItems()[3]`.

This isn't a nice way of doing it... If I add new items before it, I need to change that line and it gets even worst if I have some AsciiArt above it because depending on the size, it's not even included in the items (if the art is bigger than the width).

I'm not sure how we should do that, looping over items with getText() might be too much...

Any idea ?

**Comment by AydinHassan** [comment]
Not sure I'm following here - do you have an example maybe?

**Comment by Lynesth** [comment]
Yes of course! Here is a simple one:

```php
$menu = (new CliMenuBuilder)
    ->addAsciiArt($art)
    ->addItem('Some thing', function() { /* do something */ })
    ->addSubMenu('My sub menu')
        ->addItem('Some other thing')
        ->end()
    ->build();

// Let's say I now want to programmatically fire the 'Some thing' callback
// Currently I have to do this:
$menu->getItems()[1]->getSelectAction();

// If I want to open the sub menu:
$menu->getItems()[2]->getSelectAction();
```

There currently is no other way to select a specific item in a menu than using `getItems()`.
But now let's say the terminal width is smaller than the AsciiArt that is at the top of my menu.
It won't be included in the menu's items, won't be printed, and so all indexes are now messed up.
Same thing if I add some item at the top for example or whatever.

**Comment by AydinHassan** [comment]
@Lynesth maybe `addAsciiArt` should just throw an exception if the window is too small?

**Comment by Lynesth** [comment]
I find the fact that it isn't printed when window is too small to be a nice feature. Ascii arts usually aren't that important but may take a lot of space.

I guess one quick way to fix this would be to add a `LineBreakItem` instead of an `AsciiArt` is too big but it wouldn't solve adding the art via `addMenuItem` instead of `addAsciiArt`.

Moreover, if I end up adding new items in the menu (using `setItems` for example) it would still be an issue.

**Comment by Lynesth** [comment]
This "issue" is not going to be fixed. You can try to circle around it by first creating Items and then adding them to the menu so that you can refer to them anytime.

Closing this.
